package io.leonis.zosma.ipc.peripheral;

import java.util.function.Function;

/**
 * The Interface ControllerHandler.
 *
 * This interface describes the functionality of an object which can interpret the state of a
 * {@link Controller}.
 *
 * @param <C> The type of {@link Controller} whose controls are interpreted.
 * @param <O> The type of output generated by this handler.
 * @author Jeroen de Jong
 */
public interface ControllerHandler<C extends Controller, O> extends Function<C, O> {
}
